{"uid":"85f5583ec4b4e904","name":"test_add_product_to_cart","fullName":"tests.TestInvalidPromo#test_add_product_to_cart","historyId":"741844b037389cffca2906cbda6ca7ed","time":{"start":1728927308181,"stop":1728927308181,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55d8948f002a <unknown>\n#1 0x55d8945d65e0 <unknown>\n#2 0x55d89460e921 <unknown>\n#3 0x55d89460a2c5 <unknown>\n#4 0x55d894656df6 <unknown>\n#5 0x55d894656446 <unknown>\n#6 0x55d89464a8c3 <unknown>\n#7 0x55d8946186b3 <unknown>\n#8 0x55d89461968e <unknown>\n#9 0x55d8948baa2b <unknown>\n#10 0x55d8948be9b1 <unknown>\n#11 0x55d8948a7225 <unknown>\n#12 0x55d8948bf532 <unknown>\n#13 0x55d89488c38f <unknown>\n#14 0x55d8948def28 <unknown>\n#15 0x55d8948df0f3 <unknown>\n#16 0x55d8948eee7c <unknown>\n#17 0x7f1941494ac3 <unknown>","statusTrace":"request = <SubRequest 'init_driver' for <Function test_add_product_to_cart>>\n\n    @pytest.fixture(scope=\"class\")\n    def init_driver(request):\n        # Инициализация драйвера\n>       driver = webdriver.Chrome()\n\nconftest.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:212: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:299: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f3aa44dcb20>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: Chrome failed to sta...\\\\n#15 0x55d8948df0f3 \\\\u003Cunknown>\\\\n#16 0x55d8948eee7c \\\\u003Cunknown>\\\\n#17 0x7f1941494ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\nE         (session not created: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x55d8948f002a <unknown>\nE       #1 0x55d8945d65e0 <unknown>\nE       #2 0x55d89460e921 <unknown>\nE       #3 0x55d89460a2c5 <unknown>\nE       #4 0x55d894656df6 <unknown>\nE       #5 0x55d894656446 <unknown>\nE       #6 0x55d89464a8c3 <unknown>\nE       #7 0x55d8946186b3 <unknown>\nE       #8 0x55d89461968e <unknown>\nE       #9 0x55d8948baa2b <unknown>\nE       #10 0x55d8948be9b1 <unknown>\nE       #11 0x55d8948a7225 <unknown>\nE       #12 0x55d8948bf532 <unknown>\nE       #13 0x55d89488c38f <unknown>\nE       #14 0x55d8948def28 <unknown>\nE       #15 0x55d8948df0f3 <unknown>\nE       #16 0x55d8948eee7c <unknown>\nE       #17 0x7f1941494ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"init_driver","time":{"start":1728927308181,"stop":1728927308366,"duration":185},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55d8948f002a <unknown>\n#1 0x55d8945d65e0 <unknown>\n#2 0x55d89460e921 <unknown>\n#3 0x55d89460a2c5 <unknown>\n#4 0x55d894656df6 <unknown>\n#5 0x55d894656446 <unknown>\n#6 0x55d89464a8c3 <unknown>\n#7 0x55d8946186b3 <unknown>\n#8 0x55d89461968e <unknown>\n#9 0x55d8948baa2b <unknown>\n#10 0x55d8948be9b1 <unknown>\n#11 0x55d8948a7225 <unknown>\n#12 0x55d8948bf532 <unknown>\n#13 0x55d89488c38f <unknown>\n#14 0x55d8948def28 <unknown>\n#15 0x55d8948df0f3 <unknown>\n#16 0x55d8948eee7c <unknown>\n#17 0x7f1941494ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/Kassa/Kassa/conftest.py\", line 8, in init_driver\n    driver = webdriver.Chrome()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('init_driver', 'base_url')"},{"name":"suite","value":"tests"},{"name":"subSuite","value":"TestInvalidPromo"},{"name":"host","value":"fv-az1501-493"},{"name":"thread","value":"2268-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"f7cba018c216d3a8","reportUrl":"https://Neonila96.github.io/Kassa/6//#testresult/f7cba018c216d3a8","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55ade67c102a <unknown>\n#1 0x55ade64a75e0 <unknown>\n#2 0x55ade64df921 <unknown>\n#3 0x55ade64db2c5 <unknown>\n#4 0x55ade6527df6 <unknown>\n#5 0x55ade6527446 <unknown>\n#6 0x55ade651b8c3 <unknown>\n#7 0x55ade64e96b3 <unknown>\n#8 0x55ade64ea68e <unknown>\n#9 0x55ade678ba2b <unknown>\n#10 0x55ade678f9b1 <unknown>\n#11 0x55ade6778225 <unknown>\n#12 0x55ade6790532 <unknown>\n#13 0x55ade675d38f <unknown>\n#14 0x55ade67aff28 <unknown>\n#15 0x55ade67b00f3 <unknown>\n#16 0x55ade67bfe7c <unknown>\n#17 0x7f83a6894ac3 <unknown>","time":{"start":1728926914261,"stop":1728926914261,"duration":0}},{"uid":"be454a51057255bc","reportUrl":"https://Neonila96.github.io/Kassa/5//#testresult/be454a51057255bc","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55bacfc7402a <unknown>\n#1 0x55bacf95a5e0 <unknown>\n#2 0x55bacf992921 <unknown>\n#3 0x55bacf98e2c5 <unknown>\n#4 0x55bacf9dadf6 <unknown>\n#5 0x55bacf9da446 <unknown>\n#6 0x55bacf9ce8c3 <unknown>\n#7 0x55bacf99c6b3 <unknown>\n#8 0x55bacf99d68e <unknown>\n#9 0x55bacfc3ea2b <unknown>\n#10 0x55bacfc429b1 <unknown>\n#11 0x55bacfc2b225 <unknown>\n#12 0x55bacfc43532 <unknown>\n#13 0x55bacfc1038f <unknown>\n#14 0x55bacfc62f28 <unknown>\n#15 0x55bacfc630f3 <unknown>\n#16 0x55bacfc72e7c <unknown>\n#17 0x7f3569c94ac3 <unknown>","time":{"start":1728925937004,"stop":1728925937004,"duration":0}},{"uid":"299cd1d5a429fddb","reportUrl":"https://Neonila96.github.io/Kassa/4//#testresult/299cd1d5a429fddb","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55f96993f02a <unknown>\n#1 0x55f9696255e0 <unknown>\n#2 0x55f96965d921 <unknown>\n#3 0x55f9696592c5 <unknown>\n#4 0x55f9696a5df6 <unknown>\n#5 0x55f9696a5446 <unknown>\n#6 0x55f9696998c3 <unknown>\n#7 0x55f9696676b3 <unknown>\n#8 0x55f96966868e <unknown>\n#9 0x55f969909a2b <unknown>\n#10 0x55f96990d9b1 <unknown>\n#11 0x55f9698f6225 <unknown>\n#12 0x55f96990e532 <unknown>\n#13 0x55f9698db38f <unknown>\n#14 0x55f96992df28 <unknown>\n#15 0x55f96992e0f3 <unknown>\n#16 0x55f96993de7c <unknown>\n#17 0x7f1677c94ac3 <unknown>","time":{"start":1728925601833,"stop":1728925601833,"duration":0}}]},"tags":["@pytest.mark.usefixtures('init_driver', 'base_url')"]},"source":"85f5583ec4b4e904.json","parameterValues":[]}